### ISSUE TITLE
Incorrectly parses URLs with ports but no scheme.

### ISSUE THREAD

**Issue by sigmavirus24** [python-hyper/rfc3986#18]
There should be a way to work around this. We should strive to be better than the stdlib, not just marginally better.

``` py
>>> rfc3986.urlparse('172.25.241.180:8181/os-releases/11.1.0/')
ParseResult(scheme=u'172.25.241.180', userinfo=None, host=None, port=None, path=u'8181/os-releases/11.1.0/', query=None, fragment=None)
```

**Comment by sigmavirus24** [comment]
Actually I probably need to re-read the RFC to see if this is even valid.

**Comment by sigmavirus24** [comment]
The trick with this is that the scheme is defined as:

```
${scheme}:
```

And the authority as

```
//${authority
```

Which means that anything prior to the first `:` should be considered the scheme... if it's using the allowed characters for the scheme component. I believe we've fixed that, but this is probably still not going to work the way some people might want. We still have no good way to determine the difference between `172.25.241.180:8181` as the *intended* authority without `//` leading it.

I'll leave this open, but I think there's not much to improve upon over 1.0 in which we have a better regular expression for matching schemes.

**Comment by win911** [comment]
According to [RFC 3986](https://tools.ietf.org/html/rfc3986), the ABNF for scheme is:

scheme = ALPHA *( ALPHA / DIGIT / "+" / "-" / ".")

So I think the IP address cannot be regarded as scheme.

**Comment by SethMichaelLarson** [comment]
As far as I can tell in the latest version this works properly? (As long as a `//` is appended to the front of the URI)

```python
>>> rfc3986.urlparse("//172.25.241.180:8181/os-releases/11.1.0/")                                                                                                                                                                        
ParseResult(scheme=None, userinfo=None, host='172.25.241.180', port=8181, path='/os-releases/11.1.0/', query=None, fragment=None)
```

**Comment by sigmavirus24** [comment]
@SethMichaelLarson I believe that's the *right* way to handle this. If that's released and working we can close this.
