### ISSUE TITLE
bug report (fuzz testing)

### ISSUE THREAD

**Issue by kennethreitz** [python-hyper/rfc3986#32]
`'http+unix://%2Fvar%2Frun%2Fsocket/path?key=value'`

https://github.com/python-hyper/rfc3986/blob/4102c508661d4e12a5eb6d219d851abf85e366d4/src/rfc3986/abnf_regexp.py#L74

**Comment by SethMichaelLarson** [comment]
@sigmavirus24 Took a quick look at this and tried it locally. It parses the host and leaves the percent-encoded-ness. Could this issue be fixed with adding percent-decoding to the `rfc3986.normalizers.normalize_host()` or should we be more picky about what/when this occurs on a whole URL?

**Comment by sigmavirus24** [comment]
I think `%2Fvar%2Frun%2Fsocket` is actually the host and should be parsed as that. I don't recall what @kennethreitz was expecting here. This is no longer something I remember as to why it's a bug :/

**Comment by SethMichaelLarson** [comment]
I can investigate what the behavior was around when this issue was filed. I think how it's parsing right now is actually correct. Users should have decode percent-encoded hosts.

**Comment by SethMichaelLarson** [comment]
Looks like it parses the same now as when this issue was filed, there hasn't been a release since July 2017.

**Comment by sigmavirus24** [comment]
What happens if we do `rfc3986.urlparse('http+unix://%2Fvar%2Frun%2Fsocket/path?key=value').uri_reference.normalize()`? I think I found notes that we were losing the host at some point somewhere?

**Comment by SethMichaelLarson** [comment]
Glad you found some notes!

```python
>>> rfc3986.urlparse('http+unix://%2Fvar%2Frun%2Fsocket/path?key=value').reference.normalize()
URIReference(scheme='http+unix', authority=None, path='/path', query='key=value', fragment=None)
```

So we're losing the whole `authority` section, that's definitely not good. I'll look at this.

**Comment by sigmavirus24** [comment]
Yeah, so it's entirely likely that I had pinpointed this to a problem with REG_NAME or perhaps SUBAUTHORITY_MATCHER isn't using it?

**Comment by SethMichaelLarson** [comment]
Also side-note: I think we're being too lax on the port section within the authority regex. If there's a ":" character without a port following that shouldn't be a valid authority per the RFC.

**Comment by sigmavirus24** [comment]
That seems acceptable. I wonder if we need tests specifically for the regular expressions to show that they work the way we intended when we write them 🙃 

I'm open to being more strict about URIs too but I think we might want to open a separate issue for that.

**Comment by SethMichaelLarson** [comment]
Definitely. I'm going to give all the regular expressions another look and see if I see anything else out of place that I see. Maybe even run an ABNF -> regex tool and compare what comes out with what we have? I'll open an issue with all my findings.
