### ISSUE TITLE
http://[ffff::] deemed invalid incorrectly

### ISSUE THREAD

**Issue by RedChen** [python-hyper/rfc3986#33]
From abnf_regexp.py#110
should be changed from
`IPv6_RE = '(({0})|({1})|({2})|({3})|({4})|({5})|({6})|({7}))'.format(
    *variations
)`

to

`IPv6_RE = '(({0})|({1})|({2})|({3})|({4})|({5})|({6})|({7})|({8}))'.format(
    *variations
)
`

So, the rule 

># [ *6( h16 ":" ) h16 ] "::" 
could be applied

**Comment by sigmavirus24** [comment]
I would merge a pull request that fixes this.

**Comment by sigmavirus24** [comment]
Fixed in #34
