### ISSUE TITLE
Better handling of escaping in regex patterns

### ISSUE THREAD

**Issue by sethmlarson** [python-hyper/rfc3986#42]
Currently we erroneously accept `\\` in the `USERINFO_RE` (and probably many more!) due to regex escaping acting differently when inside or outside of a character class.

Example: `http://user\\@google.com` shouldn't be a valid URL but is accepted by us.

**Comment by sigmavirus24** [comment]
Can you add an example of this?

**Comment by sethmlarson** [comment]
Added a simple example.

**Comment by sethmlarson** [comment]
After looking at this more we do catch it when running the validator. Is this something that should only get caught at the validator stage or the parsing stage? Closing for now.
