### ISSUE TITLE
Newest release not are not shown on https://rfc3986.readthedocs.io

### ISSUE THREAD

**Issue by brot** [python-hyper/rfc3986#66]
I tried to check the release notes for the newest 1.4.0 release, but the latest release notes shown on https://rfc3986.readthedocs.io/en/latest/release-notes/index.html# are for version 1.1.0

![image](https://user-images.githubusercontent.com/36720/78755763-fd8b7400-7979-11ea-95fe-95dd8ae2fa71.png)

Then I checked the commits on github and found 25dffd665ea6d1eab29e1436e141968599eff8bc with the newest release notes.
By the way, these release notes have a bug, because the heading shows the wrong version number (1.3.0 instead 1.4.0)

**Comment by pquentin** [comment]
Indeed, the last docs builds is nearly 3 years old: https://readthedocs.org/projects/rfc3986/builds/

**Comment by sigmavirus24** [comment]
https://rfc3986.readthedocs.io/en/latest/release-notes/1.4.0.html should have those notes. Thanks for pointing this out. The ReadTheDocs integration was broken.
